#!/bin/bash
# Integration Test Script for Platinum Tier
# Tests end-to-end workflow: detection → draft → approval → execution
#
# Usage: bash integration_test.sh
# Based on tasks.md T080

set -e

echo "=========================================="
echo "Digital FTE Integration Test"
echo "=========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

PASSED=0
FAILED=0

pass() {
    echo -e "${GREEN}✓ PASS${NC}: $1"
    ((PASSED++))
}

fail() {
    echo -e "${RED}✗ FAIL${NC}: $1"
    ((FAILED++))
}

info() {
    echo -e "${BLUE}ℹ INFO${NC}: $1"
}

echo "This test validates the complete workflow:"
echo "1. Cloud agent detects event (simulated)"
echo "2. Cloud agent generates draft"
echo "3. Cloud agent syncs draft to vault"
echo "4. Local agent detects draft"
echo "5. Local agent updates Dashboard.md"
echo "6. User approves draft (simulated)"
echo "7. Local agent executes action"
echo "8. Audit trail records all steps"
echo ""

read -p "Press Enter to start integration test..."
echo ""

# ============================================
# Test 1: Simulate Event Detection
# ============================================
echo "Test 1: Simulating Event Detection"
echo "-------------------------------------------"

cd /opt/digital-fte/obsidian-vault

# Create a test event file (simulating watcher detection)
TEST_EMAIL_ID="test-$(date +%s)"
TEST_DRAFT_ID="draft-$(date +%s)"

info "Creating simulated email event..."

mkdir -p /tmp/test-events
cat > /tmp/test-events/email-event.json << EOF
{
  "type": "email_received",
  "email_id": "$TEST_EMAIL_ID",
  "from": "test@example.com",
  "subject": "Integration Test Email",
  "body": "This is a test email for integration testing.",
  "received_at": "$(date -Iseconds)"
}
EOF

if [ -f "/tmp/test-events/email-event.json" ]; then
    pass "Test event created"
else
    fail "Failed to create test event"
fi

echo ""

# ============================================
# Test 2: Draft Generation
# ============================================
echo "Test 2: Testing Draft Generation"
echo "-------------------------------------------"

info "Simulating draft generation by cloud agent..."

# Create a test draft (simulating cloud agent draft generation)
mkdir -p Pending_Approval/email

cat > "Pending_Approval/email/${TEST_DRAFT_ID}.md" << EOF
---
draft_id: $TEST_DRAFT_ID
draft_type: email_reply
created_by: cloud
created_at: $(date -Iseconds)
approval_status: pending
---

# Email Reply Draft

**Original Email:**
- From: test@example.com
- Subject: Integration Test Email
- Received: $(date -Iseconds)

**Draft Reply:**

Thank you for your email. This is an automated test reply generated by the Digital FTE system.

---

**Actions:**
- [ ] Approve and send
- [ ] Reject
- [ ] Edit and approve
EOF

if [ -f "Pending_Approval/email/${TEST_DRAFT_ID}.md" ]; then
    pass "Draft file created in Pending_Approval/email/"
else
    fail "Failed to create draft file"
fi

echo ""

# ============================================
# Test 3: Vault Synchronization
# ============================================
echo "Test 3: Testing Vault Synchronization"
echo "-------------------------------------------"

info "Committing draft to vault..."

git add "Pending_Approval/email/${TEST_DRAFT_ID}.md"
git commit -m "Integration test: Add draft ${TEST_DRAFT_ID}" &>/dev/null

if [ $? -eq 0 ]; then
    pass "Draft committed to git"
else
    fail "Failed to commit draft"
fi

info "Pushing to remote..."
git push origin master &>/dev/null

if [ $? -eq 0 ]; then
    pass "Draft pushed to remote repository"
else
    fail "Failed to push to remote (check git credentials)"
fi

echo ""

# ============================================
# Test 4: Local Agent Detection
# ============================================
echo "Test 4: Testing Local Agent Detection"
echo "-------------------------------------------"

info "Waiting for local agent to detect draft (max 2 minutes)..."
info "Note: This requires local agent to be running"

# Wait up to 2 minutes for Dashboard.md to be updated
TIMEOUT=120
ELAPSED=0
DASHBOARD_UPDATED=false

while [ $ELAPSED -lt $TIMEOUT ]; do
    if [ -f "Dashboard.md" ] && grep -q "$TEST_DRAFT_ID" Dashboard.md; then
        DASHBOARD_UPDATED=true
        break
    fi
    sleep 5
    ((ELAPSED+=5))
    echo -n "."
done

echo ""

if [ "$DASHBOARD_UPDATED" = true ]; then
    pass "Local agent detected draft and updated Dashboard.md"
else
    fail "Local agent did not update Dashboard.md within timeout"
    info "Check if local agent is running"
fi

echo ""

# ============================================
# Test 5: Approval Simulation
# ============================================
echo "Test 5: Simulating User Approval"
echo "-------------------------------------------"

if [ "$DASHBOARD_UPDATED" = true ]; then
    info "Simulating user approval in Dashboard.md..."

    # Update Dashboard.md to mark draft as approved
    # This simulates user checking the box
    sed -i "s/- \[ \] Approve and send/- [x] Approve and send/" Dashboard.md

    if grep -q "\[x\] Approve and send" Dashboard.md; then
        pass "Draft marked as approved in Dashboard.md"
    else
        fail "Failed to mark draft as approved"
    fi

    # Commit approval
    git add Dashboard.md
    git commit -m "Integration test: Approve draft ${TEST_DRAFT_ID}" &>/dev/null
    git push origin master &>/dev/null

    if [ $? -eq 0 ]; then
        pass "Approval synced to vault"
    else
        fail "Failed to sync approval"
    fi
else
    fail "Skipping approval test (Dashboard not updated)"
fi

echo ""

# ============================================
# Test 6: Action Execution
# ============================================
echo "Test 6: Testing Action Execution"
echo "-------------------------------------------"

info "Waiting for local agent to execute action (max 2 minutes)..."

# Wait for audit trail entry
TIMEOUT=120
ELAPSED=0
ACTION_EXECUTED=false

while [ $ELAPSED -lt $TIMEOUT ]; do
    if [ -f "audit_trail.jsonl" ] && grep -q "$TEST_DRAFT_ID" audit_trail.jsonl; then
        if grep "$TEST_DRAFT_ID" audit_trail.jsonl | grep -q "email_sent"; then
            ACTION_EXECUTED=true
            break
        fi
    fi
    sleep 5
    ((ELAPSED+=5))
    echo -n "."
done

echo ""

if [ "$ACTION_EXECUTED" = true ]; then
    pass "Local agent executed action (recorded in audit trail)"
else
    fail "Action not executed within timeout"
    info "Check local agent logs for errors"
fi

echo ""

# ============================================
# Test 7: Audit Trail Verification
# ============================================
echo "Test 7: Verifying Audit Trail"
echo "-------------------------------------------"

if [ -f "audit_trail.jsonl" ]; then
    pass "Audit trail file exists"

    # Count events related to this test
    EVENT_COUNT=$(grep -c "$TEST_DRAFT_ID" audit_trail.jsonl || echo "0")
    info "Found $EVENT_COUNT audit events for this test"

    if [ "$EVENT_COUNT" -ge 2 ]; then
        pass "Multiple audit events recorded (draft + action)"
    else
        fail "Insufficient audit events recorded"
    fi

    # Verify audit trail integrity
    info "Verifying audit trail integrity..."
    # This would call the audit trail verification function
    # For now, just check file is valid JSON lines
    INVALID_LINES=$(awk 'BEGIN{err=0} {if(system("echo '\''" $0 "'\'' | jq . >/dev/null 2>&1") != 0) err++} END{print err}' audit_trail.jsonl)

    if [ "$INVALID_LINES" -eq 0 ]; then
        pass "Audit trail integrity verified (all valid JSON)"
    else
        fail "Audit trail has $INVALID_LINES invalid entries"
    fi
else
    fail "Audit trail file not found"
fi

echo ""

# ============================================
# Test 8: Cleanup
# ============================================
echo "Test 8: Cleanup"
echo "-------------------------------------------"

info "Cleaning up test artifacts..."

# Remove test draft
if [ -f "Pending_Approval/email/${TEST_DRAFT_ID}.md" ]; then
    rm "Pending_Approval/email/${TEST_DRAFT_ID}.md"
    info "Removed test draft file"
fi

# Remove test event
if [ -f "/tmp/test-events/email-event.json" ]; then
    rm -rf /tmp/test-events
    info "Removed test event file"
fi

# Commit cleanup
git add -A
git commit -m "Integration test: Cleanup test artifacts" &>/dev/null
git push origin master &>/dev/null

pass "Test artifacts cleaned up"

echo ""

# ============================================
# Test 9: Performance Metrics
# ============================================
echo "Test 9: Performance Metrics"
echo "-------------------------------------------"

if [ -f "audit_trail.jsonl" ]; then
    # Calculate end-to-end latency
    DRAFT_TIME=$(grep "$TEST_DRAFT_ID" audit_trail.jsonl | grep "draft_generated" | jq -r '.wall_clock_time' | head -1)
    ACTION_TIME=$(grep "$TEST_DRAFT_ID" audit_trail.jsonl | grep "email_sent" | jq -r '.wall_clock_time' | head -1)

    if [ -n "$DRAFT_TIME" ] && [ -n "$ACTION_TIME" ]; then
        DRAFT_EPOCH=$(date -d "$DRAFT_TIME" +%s 2>/dev/null || echo "0")
        ACTION_EPOCH=$(date -d "$ACTION_TIME" +%s 2>/dev/null || echo "0")
        LATENCY=$((ACTION_EPOCH - DRAFT_EPOCH))

        info "End-to-end latency: ${LATENCY} seconds"

        if [ "$LATENCY" -lt 180 ]; then
            pass "Latency is acceptable (<3 minutes)"
        else
            fail "Latency is too high (>3 minutes)"
        fi
    else
        info "Could not calculate latency (missing timestamps)"
    fi
fi

echo ""

# ============================================
# Summary
# ============================================
echo "=========================================="
echo "Integration Test Summary"
echo "=========================================="
echo -e "${GREEN}Passed: $PASSED${NC}"
echo -e "${RED}Failed: $FAILED${NC}"
echo ""

if [ "$FAILED" -eq 0 ]; then
    echo -e "${GREEN}✓ Integration test PASSED${NC}"
    echo "All components working together correctly."
    echo ""
    echo "Verified:"
    echo "  ✓ Cloud agent draft generation"
    echo "  ✓ Vault synchronization (cloud → remote → local)"
    echo "  ✓ Local agent approval processing"
    echo "  ✓ Action execution"
    echo "  ✓ Audit trail recording"
    echo ""
    exit 0
else
    echo -e "${RED}✗ Integration test FAILED${NC}"
    echo "Some components not working correctly."
    echo ""
    echo "Troubleshooting:"
    echo "  - Check cloud agent logs: journalctl -u cloud-agent.service -n 100"
    echo "  - Check local agent is running"
    echo "  - Check vault sync status"
    echo "  - Review TROUBLESHOOTING.md"
    echo ""
    exit 1
fi
