#!/usr/bin/env python3
"""
Setup Gold Tier Vault Structure

Creates all necessary Obsidian vault folders and README files
for Gold Tier Digital FTE operation.

Usage: python scripts/setup_gold_tier_vault.py
"""

from pathlib import Path
from datetime import datetime


def create_folder_with_readme(folder_path: Path, readme_content: str):
    """Create folder and README file."""
    folder_path.mkdir(parents=True, exist_ok=True)
    readme_path = folder_path / "README.md"

    if not readme_path.exists():
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)
        print(f"✓ Created {folder_path} with README")
    else:
        print(f"✓ {folder_path} already exists")


def setup_vault_structure():
    """Setup complete Obsidian vault structure for Gold Tier."""

    vault_root = Path("obsidian-vault")

    print("\n" + "="*60)
    print("Setting up Gold Tier Obsidian Vault Structure")
    print("="*60 + "\n")

    # Briefings folder
    briefings_readme = """# Weekly CEO Briefings

This folder contains weekly executive briefings generated every Monday at 8:00 AM.

## Naming Convention

Briefings are named using ISO week format: `YYYY-WW.md`

Example: `2026-14.md` (Week 14 of 2026)

## Contents

Each briefing includes:
- Financial summary (revenue, expenses, profit/loss)
- Social media performance (posts, engagement metrics)
- Completed tasks and pending action items
- Critical issues requiring attention
- Week-over-week comparison metrics

## Generation

Briefings are automatically generated by the briefing watcher every Monday morning.
They can also be manually generated using the `generate_briefing` MCP tool.
"""
    create_folder_with_readme(vault_root / "Briefings", briefings_readme)

    # Audit Logs folder
    audit_logs_readme = """# Audit Logs

This folder contains comprehensive audit logs of all agent actions.

## Naming Convention

Audit logs are organized by date: `YYYY-MM-DD.md`

Example: `2026-04-02.md`

## Contents

Each daily log includes:
- Timestamp for each action
- Action type and name
- Parameters used
- Result or error message
- Reasoning behind the action
- User approval information (for high-risk actions)
- Safety level (0-3)

## Retention

Audit logs are retained for 7 years per constitution requirements.
Log rotation is handled automatically by the `rotate_audit_logs.py` script.

## Integrity

Logs use hash chain integrity to prevent tampering. Each entry includes
a hash of the previous entry, creating a tamper-evident chain.
"""
    create_folder_with_readme(vault_root / "Audit_Logs", audit_logs_readme)

    # Accounting folder (already exists, just verify)
    accounting_readme = """# Accounting

This folder contains business transaction records and financial data.

## Database

- `transactions.db`: SQLite database with all business transactions

## Structure

Transactions are automatically recorded from Odoo Community Edition
by the Odoo watcher with duplicate detection.

## Categories

- Revenue
- COGS (Cost of Goods Sold)
- Operating Expenses
- Assets
- Liabilities
- Equity
"""
    create_folder_with_readme(vault_root / "Accounting", accounting_readme)

    # Verify existing folders
    existing_folders = [
        "Inbox",
        "Needs_Action",
        "Done",
        "Approvals",
        "Reports",
        "Content_Queue",
        "Schedules",
        "Rejected",
        "Expired"
    ]

    print("\nVerifying existing folders:")
    for folder_name in existing_folders:
        folder_path = vault_root / folder_name
        if folder_path.exists():
            print(f"✓ {folder_name} exists")
        else:
            folder_path.mkdir(parents=True, exist_ok=True)
            print(f"✓ Created {folder_name}")

    # Create Dashboard if it doesn't exist
    dashboard_path = vault_root / "Dashboard.md"
    if not dashboard_path.exists():
        dashboard_content = f"""# Digital FTE Dashboard

**Last Updated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Quick Links

- [[Inbox]] - New items requiring attention
- [[Needs_Action]] - Pending tasks
- [[Approvals]] - Actions awaiting approval
- [[Briefings]] - Weekly CEO briefings
- [[Reports]] - Health checks and reports
- [[Accounting]] - Financial transactions

## System Status

Run `python scripts/daily_health_check.py` to check system health.

## Recent Activity

Check [[Audit_Logs]] for complete activity history.
"""
        with open(dashboard_path, 'w', encoding='utf-8') as f:
            f.write(dashboard_content)
        print(f"\n✓ Created Dashboard.md")

    print("\n" + "="*60)
    print("✓ Gold Tier vault structure setup complete!")
    print("="*60)
    print(f"\nVault location: {vault_root.absolute()}")
    print("\nNext steps:")
    print("1. Configure Odoo credentials in .env file")
    print("2. Configure social media API credentials")
    print("3. Start watchers: python watchers/odoo_watcher/watcher.py")
    print("4. Run health check: python scripts/daily_health_check.py")


if __name__ == "__main__":
    setup_vault_structure()
